grep NDUFA4P1 all.aei.coding.eb3_2.txt
grep GFI1 all.aei.coding.eb3_2.txt
grep DIRAS3 all.aei.coding.eb3_2.txt
grep FUCA1 all.aei.coding.eb3_2.txt
grep RNU5D-1 all.aei.coding.eb3_2.txt
grep BMP8B all.aei.coding.eb3_2.txt
grep DVL1 all.aei.coding.eb3_2.txt
grep WDR8 all.aei.coding.eb3_2.txt
grep TP73 all.aei.coding.eb3_2.txt
grep RPL22 all.aei.coding.eb3_2.txt
grep PRDM16 all.aei.coding.eb3_2.txt
grep PEX10 all.aei.coding.eb3_2.txt
grep TMEM52 all.aei.coding.eb3_2.txt
grep HSPA6 all.aei.coding.eb3_2.txt
grep PTPN14 all.aei.coding.eb3_2.txt
grep OBSCN all.aei.coding.eb3_2.txt
grep HIST3H2BB all.aei.coding.eb3_2.txt
grep OR11L1 all.aei.coding.eb3_2.txt
grep LRRTM1 all.aei.coding.eb3_2.txt
grep OTX1 all.aei.coding.eb3_2.txt
grep VAX2 all.aei.coding.eb3_2.txt
grep COMMD1 all.aei.coding.eb3_2.txt
grep CCDC85A all.aei.coding.eb3_2.txt
grep CYP1B1 all.aei.coding.eb3_2.txt
grep ABCG8 all.aei.coding.eb3_2.txt
grep ZFP36L2 all.aei.coding.eb3_2.txt
grep ZDBF2 all.aei.coding.eb3_2.txt
grep GPR1 all.aei.coding.eb3_2.txt
grep TIGD1 all.aei.coding.eb3_2.txt
grep MYEOV2 all.aei.coding.eb3_2.txt
grep ALDH1L1 all.aei.coding.eb3_2.txt
grep ZIC1 all.aei.coding.eb3_2.txt
grep HES1 all.aei.coding.eb3_2.txt
grep FGFRL1 all.aei.coding.eb3_2.txt
grep SPON2 all.aei.coding.eb3_2.txt
grep KIAA1530 all.aei.coding.eb3_2.txt
grep NAP1L5 all.aei.coding.eb3_2.txt
grep GAB1 all.aei.coding.eb3_2.txt
grep ADAMTS16 all.aei.coding.eb3_2.txt
grep CDH18 all.aei.coding.eb3_2.txt
grep ERAP2 all.aei.coding.eb3_2.txt
grep RHOBTB3 all.aei.coding.eb3_2.txt
grep CSF2 all.aei.coding.eb3_2.txt
grep VTRNA2-1 all.aei.coding.eb3_2.txt
grep PRIM2 all.aei.coding.eb3_2.txt
grep BTNL2 all.aei.coding.eb3_2.txt
grep ADTRP all.aei.coding.eb3_2.txt
grep FAM50B all.aei.coding.eb3_2.txt
grep PXDC1 all.aei.coding.eb3_2.txt
grep MRAP2 all.aei.coding.eb3_2.txt
grep C6orf117 all.aei.coding.eb3_2.txt
grep LIN28B all.aei.coding.eb3_2.txt
grep AIM1 all.aei.coding.eb3_2.txt
grep PLAGL1 all.aei.coding.eb3_2.txt
grep HYMAI all.aei.coding.eb3_2.txt
grep SLC22A2* all.aei.coding.eb3_2.txt
grep IGF2R all.aei.coding.eb3_2.txt
grep SLC22A3* all.aei.coding.eb3_2.txt
grep BRP44L all.aei.coding.eb3_2.txt
grep GRB10 all.aei.coding.eb3_2.txt
grep DDC all.aei.coding.eb3_2.txt
grep GLI3 all.aei.coding.eb3_2.txt
grep HECW1 all.aei.coding.eb3_2.txt
grep HOXA4 all.aei.coding.eb3_2.txt
grep HOXA3 all.aei.coding.eb3_2.txt
grep HOXA5 all.aei.coding.eb3_2.txt
grep HOXA2 all.aei.coding.eb3_2.txt
grep EVX1 all.aei.coding.eb3_2.txt
grep HOXA11 all.aei.coding.eb3_2.txt
grep TMEM60 all.aei.coding.eb3_2.txt
grep PEG10 all.aei.coding.eb3_2.txt
grep MAGI2 all.aei.coding.eb3_2.txt
grep ASB4 all.aei.coding.eb3_2.txt
grep SGCE all.aei.coding.eb3_2.txt
grep PON2 all.aei.coding.eb3_2.txt
grep PPP1R9A all.aei.coding.eb3_2.txt
grep PON1 all.aei.coding.eb3_2.txt
grep CALCR all.aei.coding.eb3_2.txt
grep PON3 all.aei.coding.eb3_2.txt
grep DLX5 all.aei.coding.eb3_2.txt
grep TFPI2 all.aei.coding.eb3_2.txt
grep CCDC71L all.aei.coding.eb3_2.txt
grep CPA4 all.aei.coding.eb3_2.txt
grep MEST all.aei.coding.eb3_2.txt
grep COPG2 all.aei.coding.eb3_2.txt
grep COPG2IT1 all.aei.coding.eb3_2.txt
grep MESTIT1 all.aei.coding.eb3_2.txt
grep KLF14 all.aei.coding.eb3_2.txt
grep SVOPL all.aei.coding.eb3_2.txt
grep FASTK all.aei.coding.eb3_2.txt
grep SLC4A2 all.aei.coding.eb3_2.txt
grep PURG all.aei.coding.eb3_2.txt
grep DLGAP2 all.aei.coding.eb3_2.txt
grep NKAIN3 all.aei.coding.eb3_2.txt
grep LY6D all.aei.coding.eb3_2.txt
grep GPT all.aei.coding.eb3_2.txt
grep KCNK9 all.aei.coding.eb3_2.txt
grep PEG13 all.aei.coding.eb3_2.txt
grep ZFAT-AS1 all.aei.coding.eb3_2.txt
grep ZFAT all.aei.coding.eb3_2.txt
grep GLIS3 all.aei.coding.eb3_2.txt
grep APBA1 all.aei.coding.eb3_2.txt
grep C9orf85 all.aei.coding.eb3_2.txt
grep FLJ46321 all.aei.coding.eb3_2.txt
grep LMX1B all.aei.coding.eb3_2.txt
grep C9orf116 all.aei.coding.eb3_2.txt
grep PHPT1 all.aei.coding.eb3_2.txt
grep EGFL7 all.aei.coding.eb3_2.txt
grep SFMBT2 all.aei.coding.eb3_2.txt
grep GATA3 all.aei.coding.eb3_2.txt
grep CTNNA3 all.aei.coding.eb3_2.txt
grep LDB1 all.aei.coding.eb3_2.txt
grep NKX6-2 all.aei.coding.eb3_2.txt
grep C10orf93 all.aei.coding.eb3_2.txt
grep C10orf91 all.aei.coding.eb3_2.txt
grep PAOX all.aei.coding.eb3_2.txt
grep VENTX all.aei.coding.eb3_2.txt
grep INPP5F all.aei.coding.eb3_2.txt
grep WT1-AS all.aei.coding.eb3_2.txt
grep WT1 all.aei.coding.eb3_2.txt
grep KCNQ1OT1 all.aei.coding.eb3_2.txt
grep PKP3 all.aei.coding.eb3_2.txt
grep AMPD3 all.aei.coding.eb3_2.txt
grep ZNF215 all.aei.coding.eb3_2.txt
grep KCNQ1DN all.aei.coding.eb3_2.txt
grep OSBPL5 all.aei.coding.eb3_2.txt
grep PHLDA2 all.aei.coding.eb3_2.txt
grep CD81 all.aei.coding.eb3_2.txt
grep TSSC4 all.aei.coding.eb3_2.txt
grep ASCL2 all.aei.coding.eb3_2.txt
grep CDKN1C all.aei.coding.eb3_2.txt
grep TSPAN32 all.aei.coding.eb3_2.txt
grep NAP1L4 all.aei.coding.eb3_2.txt
grep IGF2 all.aei.coding.eb3_2.txt
grep TH all.aei.coding.eb3_2.txt
grep IFITM1 all.aei.coding.eb3_2.txt
grep B4GALNT4 all.aei.coding.eb3_2.txt
grep TRPM5 all.aei.coding.eb3_2.txt
grep SLC22A18 all.aei.coding.eb3_2.txt
grep SLC22A18AS all.aei.coding.eb3_2.txt
grep IGF2AS all.aei.coding.eb3_2.txt
grep H19 all.aei.coding.eb3_2.txt
grep INS all.aei.coding.eb3_2.txt
grep KCNQ1 all.aei.coding.eb3_2.txt
grep RAB1B all.aei.coding.eb3_2.txt
grep ANO1 all.aei.coding.eb3_2.txt
grep DHCR7 all.aei.coding.eb3_2.txt
grep ZC3H12C all.aei.coding.eb3_2.txt
grep KBTBD3 all.aei.coding.eb3_2.txt
grep SDHD all.aei.coding.eb3_2.txt
grep NTM all.aei.coding.eb3_2.txt
grep ST8SIA1 all.aei.coding.eb3_2.txt
grep ABCC9 all.aei.coding.eb3_2.txt
grep RBP5 all.aei.coding.eb3_2.txt
grep SLC26A10 all.aei.coding.eb3_2.txt
grep SLC38A4 all.aei.coding.eb3_2.txt
grep HOXC9 all.aei.coding.eb3_2.txt
grep HOXC4 all.aei.coding.eb3_2.txt
grep CDK4 all.aei.coding.eb3_2.txt
grep E2F7 all.aei.coding.eb3_2.txt
grep DCN all.aei.coding.eb3_2.txt
grep HNF1A all.aei.coding.eb3_2.txt
grep KIAA1545 all.aei.coding.eb3_2.txt
grep FBRSL1 all.aei.coding.eb3_2.txt
grep ATP5F1EP2 all.aei.coding.eb3_2.txt
grep HTR2A all.aei.coding.eb3_2.txt
grep RB1 all.aei.coding.eb3_2.txt
grep FLJ40296 all.aei.coding.eb3_2.txt
grep FAM70B all.aei.coding.eb3_2.txt
grep FOXG1 all.aei.coding.eb3_2.txt
grep FERMT2 all.aei.coding.eb3_2.txt
grep ESR2 all.aei.coding.eb3_2.txt
grep SMOC1 all.aei.coding.eb3_2.txt
grep DIO3 all.aei.coding.eb3_2.txt
grep MEG3 all.aei.coding.eb3_2.txt
grep DLK1 all.aei.coding.eb3_2.txt
grep MEG8 all.aei.coding.eb3_2.txt
grep SNORD114-1 all.aei.coding.eb3_2.txt
grep DIO3OS all.aei.coding.eb3_2.txt
grep SNORD113-1 all.aei.coding.eb3_2.txt
grep RTL1 all.aei.coding.eb3_2.txt
grep MAGEL2 all.aei.coding.eb3_2.txt
grep ZNF127AS all.aei.coding.eb3_2.txt
grep MKRN3 all.aei.coding.eb3_2.txt
grep UBE3A all.aei.coding.eb3_2.txt
grep SNORD115@ all.aei.coding.eb3_2.txt
grep SNORD116 all.aei.coding.eb3_2.txt
grep SNORD109A all.aei.coding.eb3_2.txt
grep SNORD108 all.aei.coding.eb3_2.txt
grep SNORD115-48 all.aei.coding.eb3_2.txt
grep ATP10A all.aei.coding.eb3_2.txt
grep SNORD107 all.aei.coding.eb3_2.txt
grep SNORD109B all.aei.coding.eb3_2.txt
grep NPAP1 all.aei.coding.eb3_2.txt
grep SNRPN all.aei.coding.eb3_2.txt
grep PWCR1 all.aei.coding.eb3_2.txt
grep PWAR6 all.aei.coding.eb3_2.txt
grep GABRB3 all.aei.coding.eb3_2.txt
grep NDN all.aei.coding.eb3_2.txt
grep GABRA5 all.aei.coding.eb3_2.txt
grep GABRG3 all.aei.coding.eb3_2.txt
grep SNURF all.aei.coding.eb3_2.txt
grep SNORD64 all.aei.coding.eb3_2.txt
grep GATM all.aei.coding.eb3_2.txt
grep RASGRF1 all.aei.coding.eb3_2.txt
grep MIR184 all.aei.coding.eb3_2.txt
grep IRAIN all.aei.coding.eb3_2.txt
grep SOX8 all.aei.coding.eb3_2.txt
grep ZNF597 all.aei.coding.eb3_2.txt
grep NAA60 all.aei.coding.eb3_2.txt
grep SALL1 all.aei.coding.eb3_2.txt
grep CMTM1 all.aei.coding.eb3_2.txt
grep C16orf57 all.aei.coding.eb3_2.txt
grep ZFP90 all.aei.coding.eb3_2.txt
grep ACD all.aei.coding.eb3_2.txt
grep FOXF1 all.aei.coding.eb3_2.txt
grep TP53 all.aei.coding.eb3_2.txt
grep TMEM88 all.aei.coding.eb3_2.txt
grep PYY2 all.aei.coding.eb3_2.txt
grep HOXB2 all.aei.coding.eb3_2.txt
grep HOXB3 all.aei.coding.eb3_2.txt
grep LOC100131170 all.aei.coding.eb3_2.txt
grep IMPACT all.aei.coding.eb3_2.txt
grep BRUNOL4 all.aei.coding.eb3_2.txt
grep FAM59A all.aei.coding.eb3_2.txt
grep ZNF396 all.aei.coding.eb3_2.txt
grep TCEB3C all.aei.coding.eb3_2.txt
grep PPAP2C all.aei.coding.eb3_2.txt
grep DNMT1 all.aei.coding.eb3_2.txt
grep CHMP2A all.aei.coding.eb3_2.txt
grep TSHZ3 all.aei.coding.eb3_2.txt
grep CHST8 all.aei.coding.eb3_2.txt
grep ZNF225 all.aei.coding.eb3_2.txt
grep ZIM2 all.aei.coding.eb3_2.txt
grep ZNF264 all.aei.coding.eb3_2.txt
grep MIMT1 all.aei.coding.eb3_2.txt
grep MZF1 all.aei.coding.eb3_2.txt
grep PEG3 all.aei.coding.eb3_2.txt
grep LILRB4 all.aei.coding.eb3_2.txt
grep ZNF229 all.aei.coding.eb3_2.txt
grep MIR371A all.aei.coding.eb3_2.txt
grep NLRP2 all.aei.coding.eb3_2.txt
grep PEG3-AS1 all.aei.coding.eb3_2.txt
grep ZIM3 all.aei.coding.eb3_2.txt
grep USP29 all.aei.coding.eb3_2.txt
grep ISM1 all.aei.coding.eb3_2.txt
grep C20orf82 all.aei.coding.eb3_2.txt
grep PSIMCT-1 all.aei.coding.eb3_2.txt
grep BLCAP all.aei.coding.eb3_2.txt
grep NNAT all.aei.coding.eb3_2.txt
grep HM13 all.aei.coding.eb3_2.txt
grep MCTS2 all.aei.coding.eb3_2.txt
grep GDAP1L1 all.aei.coding.eb3_2.txt
grep SGK2 all.aei.coding.eb3_2.txt
grep COL9A3 all.aei.coding.eb3_2.txt
grep GNAS all.aei.coding.eb3_2.txt
grep L3MBTL1 all.aei.coding.eb3_2.txt
grep SANG all.aei.coding.eb3_2.txt
grep GNASAS all.aei.coding.eb3_2.txt
grep MIR298 all.aei.coding.eb3_2.txt
grep MIR296 all.aei.coding.eb3_2.txt
grep C20orf20 all.aei.coding.eb3_2.txt
grep SIM2 all.aei.coding.eb3_2.txt
grep DSCAM all.aei.coding.eb3_2.txt
grep DGCR6 all.aei.coding.eb3_2.txt
grep DGCR6L all.aei.coding.eb3_2.txt
grep FLJ20464 all.aei.coding.eb3_2.txt
grep XIST all.aei.coding.eb3_2.txt
grep TSIX all.aei.coding.eb3_2.txt
