grep -w "Gene" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "NDUFA4P1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "GFI1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "DIRAS3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "FUCA1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "RNU5D-1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "BMP8B" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "DVL1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "TP73" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "WDR8" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "RPL22" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PRDM16" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PEX10" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "TMEM52" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "HSPA6" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PTPN14" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "OBSCN" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "HIST3H2BB" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "OR11L1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "LRRTM1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "VAX2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "OTX1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "COMMD1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "CCDC85A" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "CYP1B1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ABCG8" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ZFP36L2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ZDBF2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "GPR1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "TIGD1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MYEOV2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ALDH1L1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ZIC1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "HES1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "FGFRL1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SPON2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "KIAA1530" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "NAP1L5" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "GAB1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ADAMTS16" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "CDH18" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "RHOBTB3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ERAP2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "VTRNA2-1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "CSF2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PRIM2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "BTNL2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ADTRP" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "FAM50B" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PXDC1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MRAP2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "C6orf117" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "AIM1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "LIN28B" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PLAGL1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "HYMAI" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SLC22A2*" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "IGF2R" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SLC22A3*" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "BRP44L" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "GRB10" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "DDC" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "GLI3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "HECW1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "HOXA3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "HOXA4" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "HOXA2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "HOXA11" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "EVX1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "HOXA5" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "TMEM60" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MAGI2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PEG10" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ASB4" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SGCE" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PON3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PON2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PPP1R9A" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "CALCR" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "GNG11" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PON1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "TFPI2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "DLX5" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "CCDC71L" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MEST" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "COPG2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "COPG2IT1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "CPA4" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MESTIT1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "KLF14" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SVOPL" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "FASTK" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SLC4A2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PTPRN2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PURG" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "DLGAP2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "NKAIN3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "LY6D" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PEG13" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "GPT" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "KCNK9" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ZFAT-AS1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ZFAT" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "GLIS3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "APBA1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "C9orf85" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "FLJ46321" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "LMX1B" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PHPT1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "EGFL7" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "C9orf116" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SFMBT2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "GATA3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "CTNNA3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "LDB1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "NKX6-2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "C10orf91" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "C10orf93" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "VENTX" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PAOX" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "WT1-AS" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "WT1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PKP3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "AMPD3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "OSBPL5" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "KCNQ1DN" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ZNF215" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "NAP1L4" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "CDKN1C" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "TSPAN32" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "H19" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SLC22A18AS" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "TSSC4" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "CD81" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "B4GALNT4" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SLC22A18" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PHLDA2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ASCL2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "IGF2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "TH" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "TRPM5" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "IGF2AS" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "INS" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "KCNQ1OT1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "KCNQ1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "IFITM1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "RAB1B" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ANO1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "DHCR7" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "KBTBD3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ZC3H12C" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SDHD" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "NTM" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ST8SIA1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ABCC9" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "RBP5" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SLC38A4" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SLC26A10" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "HOXC9" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "HOXC4" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "CDK4" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "E2F7" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "DCN" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "KIAA1545" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "FBRSL1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ATP5F1EP2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "HTR2A" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "RB1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "KBTBD6" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "FLJ40296" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "FAM70B" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "FOXG1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "FERMT2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SMOC1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "DIO3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MEG3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "DLK1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MEG8" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "RTL1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SNORD114-1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SNORD113-1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "DIO3OS" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MAGEL2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "UBE3A" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ZNF127AS" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MKRN3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PWCR1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PWAR6" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SNRPN" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ATP10A" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SNORD116" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SNORD115@" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SNORD108" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "NPAP1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SNORD109A" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SNORD109B" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SNORD115-48" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SNORD107" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "GABRB3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "GABRA5" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "NDN" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SNURF" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SNORD64" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "GABRG3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "GATM" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "RASGRF1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MIR184" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "IRAIN" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PRR25" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "NAA60" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SOX8" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ZNF597" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SALL1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "CMTM1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "C16orf57" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ZFP90" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ACD" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "FOXF1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "CDH15" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "TMEM88" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PYY2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "HOXB2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "HOXB3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "LOC100131170" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "IMPACT" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "CELF4" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "FAM59A" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ZNF396" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "TCEB3C" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PARD6G" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PPAP2C" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "DNMT1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "CHMP2A" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "TSHZ3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "CHST8" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ZNF225" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "AXL" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MZF1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ZNF264" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PEG3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "LILRB4" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ZIM2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ZNF229" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MIR371A" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "NLRP2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ZIM3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "USP29" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MIMT1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PEG3-AS1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "C20orf82" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ISM1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "NNAT" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "BLCAP" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "HM13" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MCTS2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "GDAP1L1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SGK2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "COL9A3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "GNAS" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "L3MBTL1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MIR298" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "GNAS-AS1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MIR296" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "C20orf20" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MIR125B2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "DSCAM" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SIM2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "DGCR6" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "DGCR6L" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "FLJ20464" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "TSIX" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "XIST" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
