grep -w "DIRAS3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "RNU5D-1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "TP73" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "LRRTM1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "COMMD1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ZDBF2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "GPR1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "NAP1L5" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "GAB1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "RHOBTB3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ERAP2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "VTRNA2-1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ADTRP" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "FAM50B" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PXDC1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "AIM1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "LIN28B" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PLAGL1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "HYMAI" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SLC22A2*" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SLC22A3*" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "GRB10" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "DDC" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "GLI3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "HECW1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "HOXA4" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MAGI2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PEG10" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ASB4" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SGCE" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PON3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PON2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PPP1R9A" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "GNG11" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "TFPI2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "CCDC71L" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MEST" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "COPG2IT1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "CPA4" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MESTIT1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "KLF14" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SVOPL" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PTPRN2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "DLGAP2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PEG13" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "KCNK9" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ZFAT-AS1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ZFAT" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "GLIS3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SFMBT2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "WT1-AS" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "WT1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "AMPD3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "OSBPL5" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "KCNQ1DN" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "CDKN1C" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "TSPAN32" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "H19" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "TSSC4" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "CD81" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SLC22A18" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PHLDA2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ASCL2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "IGF2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "IGF2AS" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "INS" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "KCNQ1OT1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "KCNQ1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ANO1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "DHCR7" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ZC3H12C" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "NTM" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ST8SIA1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "RBP5" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ATP5F1EP2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "RB1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "KBTBD6" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SMOC1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "DIO3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MEG3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "DLK1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MEG8" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "RTL1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SNORD114-1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SNORD113-1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "DIO3OS" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MAGEL2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "UBE3A" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MKRN3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PWCR1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PWAR6" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SNRPN" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ATP10A" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SNORD116" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SNORD115@" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SNORD108" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "NPAP1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SNORD109A" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SNORD109B" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SNORD115-48" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SNORD107" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "NDN" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SNURF" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SNORD64" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "RASGRF1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "IRAIN" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PRR25" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "NAA60" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ZNF597" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "CMTM1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ZFP90" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "CDH15" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "IMPACT" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ZNF396" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "TCEB3C" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PARD6G" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "DNMT1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "AXL" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PEG3" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "ZIM2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MIR371A" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "NLRP2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MIMT1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "PEG3-AS1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "NNAT" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "BLCAP" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MCTS2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "GDAP1L1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "SGK2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "GNAS" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "L3MBTL1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MIR298" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "GNAS-AS1" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MIR296" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "MIR125B2" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "DSCAM" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "DGCR6" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "DGCR6L" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "TSIX" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
grep -w "XIST" ucsc.refseq.hg19.txn.whole.gene.sorted.nochr.bed >> hg19.imprinted.genes.txt
